# Generated by Django 6.0.4 on 2026-05-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zunzun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrpstatus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
