# Generated by Django 6.0.4 on 2026-05-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zunzun", "0002_lrpstatus_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lrpstatus",
            name="current_status",
            field=models.TextField(default="Initializing"),
        ),
    ]
