# Generated by Django 6.0.5 on 2026-06-01 19:31

import django.db.models.deletion
import secrets
import zunzun.session_helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zunzun", "0005_remove_lrpstatus_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="lrpstatus",
            name="owner_ip",
            field=models.CharField(db_index=True, default="", max_length=45),
        ),
        migrations.AddField(
            model_name="lrpstatus",
            name="owner_session_key",
            field=models.CharField(db_index=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="lrpstatus",
            name="result_token",
            field=models.CharField(
                db_index=True, default=secrets.token_urlsafe, max_length=43, unique=True
            ),
        ),
        migrations.CreateModel(
            name="LRPDispatchData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data",
                    models.JSONField(default=dict, encoder=zunzun.session_helpers.NumpyJSONEncoder),
                ),
                (
                    "functionfinder",
                    models.JSONField(default=dict, encoder=zunzun.session_helpers.NumpyJSONEncoder),
                ),
                (
                    "status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_data",
                        to="zunzun.lrpstatus",
                    ),
                ),
            ],
        ),
    ]
